# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import game_pb2 as game__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\x1a\ngame.proto\"q\n\x0b\x43hatMessage\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0f\n\x07room_id\x18\x02 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x1f\n\x04type\x18\x05 \x01(\x0e\x32\x11.chat.MessageType\"`\n\nWsEnvelope\x12!\n\x04\x63hat\x18\x01 \x01(\x0b\x32\x11.chat.ChatMessageH\x00\x12$\n\x04game\x18\x02 \x01(\x0b\x32\x14.livewar.GameMessageH\x00\x42\t\n\x07payload*\xd8\x01\n\x0bMessageType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06SYSTEM\x10\x01\x12\r\n\tUSER_TEXT\x10\x02\x12\x0f\n\x0bQUERY_COUNT\x10\x03\x12\x0e\n\nROOM_COUNT\x10\x04\x12\t\n\x05MUSIC\x10\x05\x12\x0b\n\x07\x44RAWING\x10\x06\x12\x13\n\x0f\x44RAWING_REQUEST\x10\x07\x12\x11\n\rDRAWING_CLEAR\x10\x08\x12\x11\n\rDRAWING_STATE\x10\t\x12\x10\n\x0c\x44RAWING_STOP\x10\n\x12\x1b\n\x17\x44RAWING_REQUEST_APPROVE\x10\x0b\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGETYPE']._serialized_start=246
  _globals['_MESSAGETYPE']._serialized_end=462
  _globals['_CHATMESSAGE']._serialized_start=32
  _globals['_CHATMESSAGE']._serialized_end=145
  _globals['_WSENVELOPE']._serialized_start=147
  _globals['_WSENVELOPE']._serialized_end=243
# @@protoc_insertion_point(module_scope)
